package(default_visibility = ["//visibility:public"])

java_library(
    name = "sqlfu",
    srcs = glob(["*.java"]),
    deps = [
        "//java/denvr/annotations",
        "@com_google_code_findbugs_jsr305",
        "@com_google_guava",
    ]
)
