package(default_visibility = ["//visibility:public"])

java_library(
    name = "api",
    srcs = glob(["*.java"]),
    deps = [
        "//java/sqlfu/annotations",
        "@com_google_code_findbugs_jsr305",
    ],
)
