package(
    default_visibility = ["//visibility:public"],
    default_testonly = 1,
)

java_library(
    name = "AssertThrows",
    srcs = ["AssertThrows.java"],
)

java_library(
    name = "GuiceRule",
    srcs = ["GuiceRule.java"],
    deps = [
        "@com_google_inject_guice",
        "@junit",
    ]
)
